baseURL: https://www.martins.fm/
languageCode: en-us
title: Martins Tech & Sec Blog
theme: "PaperMod"
defaultTheme: light
markup:
  goldmark:
    renderer:
      unsafe: true

params:
    profileMode:
        enabled: true
        title: "Hello There 👋" # optional default will be site title
        subtitle: "<p align='left'> My name is João Martins and I live in Porto, Portugal 🇵🇹 <br> I'm an engineer with 10 years experience creating robust platforms, building teams from scratch and helping companies to protect and grow the business. I have led teams both onshore and offshore and have managed folks throughout their career journey. This blog is a place to explore interesting tech & security topics as well as personal & career development. I would like to share with you what I have struggled with and what I have learned so far. Thank you for reading! </p>"
        imageUrl: "joaofoto.jpg" # optional
        imageTitle: "<title of image as alt>" # optional
        imageWidth: 120 # custom size
        imageHeight: 120 # custom size
        buttons:
            - name: Enter Blog
              url: "/posts"

    socialIcons: # optional
        - name: "LinkedIn"
          url: "https://www.linkedin.com/in/joao-martins-tech/"
        - name: "Twitter"
          url: "https://www.linkedin.com/in/joao-martins-tech/"
        - name: "RSS"
          url: "/index.xml"  
        - name: "Email"
          url: "mailto://blog@martins.fm"  
    outputs:
      home:
        - HTML
        - RSS
        - JSON # is necessary

    fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

    ShareButtons: ["linkedin", "twitter", "reddit"]
    ShowReadingTime: true
    ShowToc: true
    ShowBreadCrumbs: true
    author: João Martins

    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
menu:
    main:
        - identifier: posts
          name: blog
          url: /posts/
          weight: 10    
        - identifier: about
          name: about me
          url: /about/
          weight: 20
        - identifier: cv
          name: cv
          url: /cv/
          weight: 30          
        - identifier: search
          name: search
          url: /search/
          weight: 40
        - identifier: tags
          name: tags
          url: /tags/
          weight: 50

         